const MB_VERSION = 4;
const DEFAULT_ITEMS = [
  // ── OOH / 아나모픽 (67) ─────────────────────────────────────────────
  { id:'ooh_001', cat:'ooh', type:'youtube', vid:'W3QwiNlsqeY', title:'Crazy 3D Billboards!', desc:'Compilation of 3D anamorphic billboard examples worldwide', src:'What in the World?' },
  { id:'ooh_002', cat:'ooh', type:'youtube', vid:'5fGldibm_UM', title:'The Most Insane 3D Augmented Reality Billboard', desc:'Showcase of cutting-edge 3D outdoor advertising technology', src:'BrandXR' },
  { id:'ooh_003', cat:'ooh', type:'youtube', vid:'Y2KKzWuvXoI', title:'Christmas Shop — Anamorphic LED Display 3D Billboard DOOH', desc:'Christmas 2024 anamorphic 3D LED billboard in Texas by Sue Sha', src:'SUE SHA' },
  { id:'ooh_004', cat:'ooh', type:'youtube', vid:'hF9rrmtHqb0', title:'Naked Eye 3D LED Display — DOOH Billboard 2024, Times Square NY', desc:'Professional anamorphic 3D content for Times Square LED screen by Sue Sha', src:'SUE SHA' },
  { id:'ooh_005', cat:'ooh', type:'youtube', vid:'oAkgIs07sI4', title:'3D Anamorphic Billboards', desc:'Award-winning 3D billboard reel from Groove Jones studio', src:'Groove Jones' },
  { id:'ooh_006', cat:'ooh', type:'youtube', vid:'6RjAKRaqZXM', title:'3D & Anamorphic Video Content — SNA Displays', desc:'Collection of 3D/anamorphic content on SNA Displays LED spectaculars', src:'SNA Displays' },
  { id:'ooh_007', cat:'ooh', type:'youtube', vid:'QQSCYwAT-ts', title:'AT&T\'s 3D Anamorphic Billboard for Recruiting Talent', desc:'Groove Jones × AT&T recruitment campaign on Discovery Green anamorphic screen', src:'Groove Jones' },
  { id:'ooh_008', cat:'ooh', type:'youtube', vid:'nRlZIhHKG1g', title:'3D Anamorphic Billboard', desc:'3D animation on an innovative media facade with 3D mapping', src:'Innotech Visuals' },
  { id:'ooh_009', cat:'ooh', type:'youtube', vid:'d_RMe7_fx-k', title:'Telkom Winter 2024 3D Anamorphic Billboard South Africa', desc:'Telkom anamorphic 3D billboard at in-store exhibition, South Africa', src:'Afriten Technologies' },
  { id:'ooh_010', cat:'ooh', type:'youtube', vid:'dlVX_0fmj6M', title:'3D Outdoor Naked Eye LED Display with Corner Design', desc:'Anamorphic illusion on giant corner LED screen by NSELED', src:'NSELED Visual World' },
  { id:'ooh_011', cat:'ooh', type:'youtube', vid:'ncJMvhSQAG8', title:'Outdoor Naked Eye 3D LED Video Wall Curved Corner Solution', desc:'Smooth seamless corner-spliced naked-eye 3D LED wall demo', src:'JYLED-Neeson' },
  { id:'ooh_012', cat:'ooh', type:'youtube', vid:'-4KimBuXqUM', title:'Naked Eye Outdoor 3D LED Billboard', desc:'Explainer and demo of outdoor naked-eye 3D LED billboard mechanics', src:'Video Monkey LED' },
  { id:'ooh_013', cat:'ooh', type:'youtube', vid:'l_ZhCKeHOFI', title:'Outdoor LED Display Naked Eye 3D Screen', desc:'LCF outdoor LED display showcasing naked-eye 3D advertising content', src:'LCF LED Display' },
  { id:'ooh_014', cat:'ooh', type:'youtube', vid:'o-6uDdwBbQY', title:'Outdoor 3D Screen — Naked Eye 3D LED Screen Supplier', desc:'Shenzhen manufacturer demo of outdoor naked-eye 3D LED corner screen', src:'Shenzhen Led Display Screen' },
  { id:'ooh_015', cat:'ooh', type:'youtube', vid:'UGrsWT2FfV0', title:'Vivo\'s Stunning Naked Eye 3D LED Display — ADHAIWELL 2024', desc:'Mind-blowing Vivo smartphone naked-eye 3D LED display by Adhaiwell', src:'Adhaiwell' },
  { id:'ooh_016', cat:'ooh', type:'youtube', vid:'-6HVSkEwons', title:'Naked-eye 3D Billboard, Outdoor LED Screen', desc:'Naked-eye 3D billboard short demo on outdoor LED screen', src:'SmartShow-LEDscreen' },
  { id:'ooh_017', cat:'ooh', type:'youtube', vid:'L3KMP5r06Ys', title:'Large Outdoor Naked-Eye 3D Displays — LED CHINA 2025', desc:'Chainzone large outdoor naked-eye 3D displays at LED CHINA 2025', src:'LED CHINA' },
  { id:'ooh_018', cat:'ooh', type:'youtube', vid:'EqPvgMv-xQw', title:'Outdoor Naked-eye 3D Applications', desc:'Showcase of outdoor naked-eye 3D display applications on buildings', src:'MINVOL' },
  { id:'ooh_019', cat:'ooh', type:'youtube', vid:'KGhlD9m4FiA', title:'Outdoor Naked Eye 3D Screen in PAVILION Shopping Center', desc:'Naked-eye 3D LED screen at Pavilion Shopping Center', src:'hiledtech' },
  { id:'ooh_020', cat:'ooh', type:'youtube', vid:'JO7-iGCmq4o', title:'Esdlumen\'s 500 sqm Naked-eye 3D LED Display at Nanjing', desc:'500-square-meter naked-eye 3D LED screen at Sun Hung Kai Centre, Nanjing', src:'Esdlumen' },
  { id:'ooh_021', cat:'ooh', type:'youtube', vid:'2qxGxMJ19Q4', title:'Outdoor Naked Eye 3D Full Color Screen', desc:'Full-color naked-eye 3D outdoor LED screen demo', src:'Arben Vision' },
  { id:'ooh_022', cat:'ooh', type:'youtube', vid:'mbnHxXi_WF0', title:'Chainzone Display — Large Outdoor Naked-eye 3D Screen E4 Series', desc:'Chainzone E4 Series large outdoor naked-eye 3D LED screen showcase', src:'Chainzone' },
  { id:'ooh_023', cat:'ooh', type:'youtube', vid:'-rXFQKYqwE0', title:'Wave by d\'strict (Anamorphic LED screen)', desc:'d\'strict\'s internationally acclaimed anamorphic wave illusion on large LED screen', src:'neidermeyer' },
  { id:'ooh_024', cat:'ooh', type:'youtube', vid:'qtykJWtnYs8', title:'Speaking Rock Texas — Anamorphic 3D LED Display Billboard 2025', desc:'Anamorphic 3D LED billboard content for Speaking Rock Texas by Sue Sha', src:'SUE SHA' },
  { id:'ooh_025', cat:'ooh', type:'youtube', vid:'n_2lm-_sMvk', title:'St. Valentine\'s Day — Anamorphic Screen 3D LED Display Billboard 2025', desc:'Valentine\'s Day anamorphic 3D LED billboard by Sue Sha / direction.view', src:'SUE SHA' },
  { id:'ooh_026', cat:'ooh', type:'youtube', vid:'FvDV8PFuPVY', title:'Halloween Anamorphic Screen 3D LED Display DOOH Billboard 2025', desc:'Halloween-themed anamorphic 3D DOOH billboard by Sue Sha', src:'SUE SHA' },
  { id:'ooh_027', cat:'ooh', type:'youtube', vid:'rkdOXXCOwGo', title:'Breakdown of 3D Billboard Anamorphic — Samsung Mobile', desc:'Behind-the-scenes breakdown of anamorphic 3D billboard for Samsung mobile in C4D', src:'PALXASH' },
  { id:'ooh_028', cat:'ooh', type:'youtube', vid:'FYt7APUzMhQ', title:'Easter — Anamorphic Screen 3D Naked Eye LED Display Billboard 2025', desc:'Easter anamorphic 3D LED DOOH billboard by Sue Sha / direction.view', src:'SUE SHA' },
  { id:'ooh_029', cat:'ooh', type:'youtube', vid:'t1BV0uoGO3I', title:'Independence Day — Anamorphic Screen 3D LED Display Billboard 2025', desc:'Independence Day themed anamorphic 3D LED billboard by Sue Sha', src:'SUE SHA' },
  { id:'ooh_030', cat:'ooh', type:'youtube', vid:'qklyDNoQ-BI', title:'3D Illusion on South Korea\'s Largest LED Screen', desc:'Jaw-dropping 3D anamorphic illusion on South Korea\'s largest high-resolution LED screen', src:'Stern Facts' },
  { id:'ooh_031', cat:'ooh', type:'youtube', vid:'Brc9GJA2XUI', title:'Watsons 3D Anamorphic Content — Pavilion Elite LED Screen', desc:'3D anamorphic content for Watsons on Pavilion Elite LED screen', src:'FrameMotion Studio' },
  { id:'ooh_032', cat:'ooh', type:'youtube', vid:'l1HhyHBUhY8', title:'This 3D LED Screen Looks Unreal — Korea Pavilion Osaka Expo 2025', desc:'Stunning naked-eye 3D LED at Korea Pavilion, Osaka-Kansai Expo 2025', src:'Shilky Sharma' },
  { id:'ooh_033', cat:'ooh', type:'youtube', vid:'LF3heX3js40', title:'How to Make 3D Anamorphic Billboards in Cinema 4D — NAB 2025', desc:'Noseman/Maxon tutorial on creating anamorphic billboards in Cinema 4D at NAB 2025', src:'Maxon' },
  { id:'ooh_034', cat:'ooh', type:'youtube', vid:'sPGLG_8oz5o', title:'Next-Level 3D Anamorphic LED Screen — Dubai', desc:'3D anamorphic LED screen technology showcase, Dubai content production', src:'Mind Spirit Design' },
  { id:'ooh_035', cat:'ooh', type:'youtube', vid:'CZxKdgiisAU', title:'Public Media Art WAVE Full ver. — d\'strict', desc:'d\'strict\'s landmark COEX anamorphic wave illusion — the work that defined the genre', src:'d\'strict' },
  { id:'ooh_036', cat:'ooh', type:'youtube', vid:'WsXuqfg7llk', title:'Who\'s Behind the Waterfall Media Art that Flooded Times Square?', desc:'Korea NOW documentary on d\'strict\'s Times Square waterfall DOOH installation', src:'KOREA NOW' },
  { id:'ooh_037', cat:'ooh', type:'youtube', vid:'2sCraZSoOzE', title:'3D Anamorphic Billboards DOOH Biggest Brands — Territory Studio', desc:'Territory Studio reel of 3D anamorphic DOOH content for major global brands', src:'David Sheldon-Hicks' },
  { id:'ooh_038', cat:'ooh', type:'youtube', vid:'6G3wB1O7s0Q', title:'Volvo EM90 — Anamorphic Billboard DOOH, Shanghai Airport', desc:'Territory Studio anamorphic 3D billboard for Volvo EM90 at Shanghai airport', src:'David Sheldon-Hicks' },
  { id:'ooh_039', cat:'ooh', type:'youtube', vid:'u7yQffsA6uo', title:'Volvo EM90 — Beijing Airport DOOH 3D Anamorphic Billboard', desc:'Territory Studio 3D anamorphic billboard for new Volvo EM90 at Beijing Airport', src:'David Sheldon-Hicks' },
  { id:'ooh_040', cat:'ooh', type:'youtube', vid:'fclcnaw33g8', title:'SUPERBIEN — MLS & Apple TV+ 3D Billboard', desc:'SUPERBIEN\'s 3D anamorphic OOH campaign for Major League Soccer × Apple TV+ partnership', src:'SUPERBIEN' },
  { id:'ooh_041', cat:'ooh', type:'youtube', vid:'wV8ttSq857M', title:'3D Billboard — Super Bowl LVII & National Football League', desc:'Award-winning 3D anamorphic billboard for NFL at Super Bowl LVII, Phoenix Arizona', src:'VIZTEK Studios' },
  { id:'ooh_042', cat:'ooh', type:'youtube', vid:'WRBsDTZDzk0', title:'Go2 Production — Burt\'s Bees 3D Anamorphic Masterpiece in DOOH', desc:'Go2 Productions × Burt\'s Bees 3D forced perspective DOOH in Toronto', src:'Go2 Productions' },
  { id:'ooh_043', cat:'ooh', type:'youtube', vid:'R5_taGbf0Dc', title:'Go2 Productions Elevates Doritos with 3D Anamorphic Animation', desc:'Go2 Productions transforms Toronto DOOH for Doritos with 3D anamorphic animation', src:'Go2 Productions' },
  { id:'ooh_044', cat:'ooh', type:'youtube', vid:'0N0n5KPs31Y', title:'Go2 Productions and Volkswagen: 3D Forced Perspective DOOH Magic', desc:'Go2 Productions × Volkswagen 3D anamorphic forced perspective DOOH campaign', src:'Go2 Productions' },
  { id:'ooh_045', cat:'ooh', type:'youtube', vid:'G9ITY0aELeU', title:'Go2 Productions — CNE Forced Perspective DOOH Advertisement', desc:'Canadian National Exhibition 3D forced perspective DOOH ad by Go2 Productions', src:'Go2 Productions' },
  { id:'ooh_046', cat:'ooh', type:'youtube', vid:'Xl2K57f88tY', title:'Starbucks DOOH 3D Anamorphic Effect Vancouver', desc:'Starbucks digital out-of-home 3D anamorphic effect billboard in Vancouver', src:'Go2 Productions' },
  { id:'ooh_047', cat:'ooh', type:'youtube', vid:'DLRrKgRXBxk', title:'BMW 3D Digital Out-of-Home DOOH Advertisement Vancouver', desc:'BMW 3D digital DOOH advertisement created by Go2 Productions, Vancouver', src:'Go2 Productions' },
  { id:'ooh_048', cat:'ooh', type:'youtube', vid:'9YpEodQbo80', title:'Burt\'s Bees 3D Anamorphic Forced Perspective Vancouver', desc:'Go2 Productions\' 3D anamorphic forced perspective billboard for Burt\'s Bees', src:'Go2 Productions' },
  { id:'ooh_049', cat:'ooh', type:'youtube', vid:'dMDG0VEroKI', title:'Doritos 3D Anamorphic and Forced Perspective Animation Vancouver', desc:'Doritos 3D anamorphic forced perspective animation billboard, Vancouver', src:'Go2 Productions' },
  { id:'ooh_050', cat:'ooh', type:'youtube', vid:'ZMb4JEZ85vI', title:'3D Anamorphic Billboard — Groove Jones', desc:'Groove Jones 3D anamorphic billboard showcase reel 2024', src:'Groove Jones' },
  { id:'ooh_051', cat:'ooh', type:'youtube', vid:'0Doxe2P2nLg', title:'Charles Schwab — Investment Themes Anamorphic Billboard', desc:'Groove Jones × Charles Schwab OOH anamorphic investment themes campaign', src:'Groove Jones' },
  { id:'ooh_052', cat:'ooh', type:'youtube', vid:'TRVxdKmUsZ0', title:'3D Billboards in Times Square — Midtown Manhattan 2024', desc:'Collection of 3D billboard sightings in Times Square, NYC, October 2024', src:'AnikoM' },
  { id:'ooh_053', cat:'ooh', type:'youtube', vid:'dyOvFovDR5w', title:'3D Billboards Times Square, New York City', desc:'3D billboard compilation from Times Square, New York City, October 2024', src:'NokDice Diary' },
  { id:'ooh_054', cat:'ooh', type:'youtube', vid:'kZ602ue6S6Q', title:'3D Billboard New York City Times Square', desc:'3D billboard sighting at Times Square NYC December 2024', src:'Travel Man TV' },
  { id:'ooh_055', cat:'ooh', type:'youtube', vid:'fpR2MI2W6CE', title:'Amazing 3D Billboard in NYC', desc:'Short clip of 3D anamorphic billboard in New York City', src:'3D Planet' },
  { id:'ooh_056', cat:'ooh', type:'youtube', vid:'JkSgQTnVYZ4', title:'Amazing Diwali 3D Billboard at Times Square!', desc:'FOOH 3D billboard video homage to Diwali festival of lights, Times Square', src:'LUCID DREAMS' },
  { id:'ooh_057', cat:'ooh', type:'youtube', vid:'cl7NNwbe1UY', title:'Ted 3D Billboard in Times Square', desc:'Ted character 3D billboard sighting in Times Square New York', src:'The Travel Dove' },
  { id:'ooh_058', cat:'ooh', type:'youtube', vid:'xQ-JFQ11Qzg', title:'LEGO 3D Billboard in Times Square', desc:'LEGO brand 3D anamorphic billboard displayed in Times Square NYC', src:'The Travel Dove' },
  { id:'ooh_059', cat:'ooh', type:'youtube', vid:'52ItCHABtmA', title:'Play Has No Limits — 3D Ad for PlayStation', desc:'BCN Visuals reimagines PlayStation iconic symbols in global 3D anamorphic campaign 2025', src:'BCN Visuals' },
  { id:'ooh_060', cat:'ooh', type:'youtube', vid:'gzCKpSwwClc', title:'International 3D Activations — Built for Scale', desc:'BCN Visuals global 3D anamorphic activations for large-scale campaigns', src:'BCN Visuals' },
  { id:'ooh_061', cat:'ooh', type:'youtube', vid:'u8s84D97KSo', title:'Best 3D OOH Campaigns — BCN Visuals', desc:'BCN Visuals\' most iconic 3D billboards: NYC, Madrid, Milan, Paris', src:'BCN Visuals' },
  { id:'ooh_062', cat:'ooh', type:'youtube', vid:'d_knNLxLVMY', title:'AVATAR The Way Of Water — 3D Billboards', desc:'Avatar: The Way of Water 3D anamorphic billboard campaign by BCN Visuals', src:'BCN Visuals' },
  { id:'ooh_063', cat:'ooh', type:'youtube', vid:'eexnfBr-dkY', title:'3D Pepsi Wild Cherry & Cream Billboard — Zinestage', desc:'Technical record of large-scale 3D anamorphic Pepsi billboard by Zinestage', src:'Zinestage' },
  { id:'ooh_064', cat:'ooh', type:'youtube', vid:'XEsVRnJRYWA', title:'Galaxy S25 Ultra 3D Anamorphic at Pavilion KL', desc:'Samsung Galaxy S25 Ultra 3D anamorphic content at Pavilion KL LED screen', src:'FrameMotion Studio' },
  { id:'ooh_065', cat:'ooh', type:'youtube', vid:'mGz7xOXxj1Y', title:'CeraVe Moisturising Cream 3D Anamorphic Billboard — Axis-0', desc:'CeraVe 3D anamorphic OOH campaign at Fahrenheit88 billboard, Kuala Lumpur', src:'Axis-0' },
  { id:'ooh_066', cat:'ooh', type:'youtube', vid:'4CUJzNlDdvw', title:'3D Movable Anamorphic Corner LED Display — Dubai UAE', desc:'Movable 3D anamorphic corner LED display for digital advertising in Dubai', src:'Volkanoo LED Displays Screens' },
  { id:'ooh_067', cat:'ooh', type:'youtube', vid:'eNzgZn2_BsM', title:'3D Anamorphic Content Showreel — All Space BKK', desc:'3D anamorphic content showreel demonstrating visual striking OOH engagement', src:'All Space BKK' },

  // ── 인터랙티브 (63) ─────────────────────────────────────────────────
  { id:'int_001', cat:'interactive', type:'youtube', vid:'RzUFtZRk1vc', title:'teamLab Planets vs teamLab Borderless Tokyo Japan 2025 UPDATE', desc:'Comparison and walkthrough of both teamLab Tokyo experiences with 2025 updates', src:'PhatLife Project' },
  { id:'int_002', cat:'interactive', type:'youtube', vid:'dLz7ezVhwG8', title:'TeamLab Borderless — Azabudai Hills, Tokyo', desc:'teamLab Borderless reopened Feb 2024 in Azabudai Hills — immersive digital art world', src:'Japan Experience' },
  { id:'int_003', cat:'interactive', type:'youtube', vid:'em4NsIbNIvg', title:'TeamLab Planets in Tokyo — New and Expanded for 2025! (4K)', desc:'TeamLab Planets Tokyo expanded experience walkthrough 4K 2025', src:'Tourist in Japan' },
  { id:'int_004', cat:'interactive', type:'youtube', vid:'pOqAf1HR5HU', title:'Scenes from TeamLab Planets in Tokyo — August 2024', desc:'First-person footage from TeamLab Planets Tokyo, August 2024', src:'Interesting Things' },
  { id:'int_005', cat:'interactive', type:'youtube', vid:'mGlKzq0YELg', title:'Adventures in Japan: Sensory Art at Tokyo\'s Teamlabs Planets', desc:'Immersive walkthrough of TeamLab Planets Tokyo sensory art installation', src:'Adventures with Sarah' },
  { id:'int_006', cat:'interactive', type:'youtube', vid:'l6W3L9kDzqk', title:'teamLab Planets TOKYO Recognized by GUINNESS WORLD RECORDS', desc:'teamLab Planets Tokyo named most visited museum by single art group — Guinness 2024', src:'BusinessWire' },
  { id:'int_007', cat:'interactive', type:'youtube', vid:'-DtLKZLol4A', title:'teamLab Borderless: MORI Building DIGITAL ART MUSEUM Highlight Video', desc:'Official teamLab Borderless highlight reel — Azabudai Hills Tokyo, opened Feb 2024', src:'teamLab' },
  { id:'int_008', cat:'interactive', type:'youtube', vid:'nnVVPdhUFIA', title:'Become Immersed Concept Video — teamLab Borderless', desc:'teamLab Borderless concept video: Azabudai Hills Tokyo immersive digital art museum', src:'teamLab' },
  { id:'int_009', cat:'interactive', type:'youtube', vid:'yaKsRkDvcrc', title:'Co-create the World Together Concept Video — teamLab Borderless', desc:'teamLab Borderless Azabudai Hills concept video on co-creation through digital art', src:'teamLab' },
  { id:'int_010', cat:'interactive', type:'youtube', vid:'u_XYqBVlx1g', title:'4K 2025 Best Digital Art — TeamLabs Borderless Tokyo', desc:'4K footage of TeamLab Borderless digital art museum, Tokyo 2024-2025', src:'Epic Treks in 4K' },
  { id:'int_011', cat:'interactive', type:'youtube', vid:'U5WSttUFWMo', title:'The Wind of New York by Refik Anadol — Sept 2024', desc:'Refik Anadol\'s The Wind of New York large-scale AI data painting installation', src:'UNITED MEDIA NEWS' },
  { id:'int_012', cat:'interactive', type:'youtube', vid:'TUaFxTHni00', title:'DATALAND by Refik Anadol — World\'s First AI Art Museum', desc:'DATALAND, the world\'s first AI art museum by Refik Anadol — intersection of tech and creativity', src:'STIR' },
  { id:'int_013', cat:'interactive', type:'youtube', vid:'NhfAPABwm7g', title:'Refik Anadol \'Echoes of the Earth\' at Futura Seoul 2024', desc:'Refik Anadol\'s AI-meets-art exhibition at Futura Seoul\'s inaugural show 2024', src:'AaronJeong' },
  { id:'int_014', cat:'interactive', type:'youtube', vid:'ZXiKwNXKS6c', title:'Introducing DATALAND — World\'s First Museum of AI Arts', desc:'Official announcement of DATALAND AI arts museum by Refik Anadol, opening 2025 at The Grand LA', src:'DATALAND' },
  { id:'int_015', cat:'interactive', type:'youtube', vid:'lwH0tXn72_Q', title:'Refik Anadol \'Coral\' at The Summit of the Future — United Nations HQ', desc:'Refik Anadol\'s \'Coral\' at UN HQ Summit of the Future, Sept 2024', src:'UNITED MEDIA NEWS' },
  { id:'int_016', cat:'interactive', type:'youtube', vid:'kvswygtOJt0', title:'Press Conference — Futura Seoul Inaugural Exhibition — Refik Anadol 2024', desc:'Refik Anadol press conference at Futura Seoul inaugural exhibition, August 2024', src:'FUTURA SEOUL' },
  { id:'int_017', cat:'interactive', type:'youtube', vid:'tPGlNLlfYNY', title:'TALK — Refik Anadol × Hans Ulrich Obrist × Yiyun Kang 2024', desc:'Artist talk: Refik Anadol, Hans Ulrich Obrist, and KAIST\'s Yiyun Kang at Futura Seoul 2024', src:'FUTURA SEOUL' },
  { id:'int_018', cat:'interactive', type:'youtube', vid:'RxCbQQDo4SY', title:'OUCHHH\'s AI Data Painting at XRP Ledger Apex Conference, Amsterdam', desc:'OUCHHH immersive AI data painting installation at Ripple XRP Ledger Apex, 2024', src:'designboom' },
  { id:'int_019', cat:'interactive', type:'youtube', vid:'DGtYO3IOzBQ', title:'Wisdom of AI Light — Ouchhh Studio × Barco', desc:'OUCHHH Studio\'s Illuminate Pavilion with Barco projectors — AI light art 2024', src:'Barco Entertainment' },
  { id:'int_020', cat:'interactive', type:'youtube', vid:'F0mNQSjN2Cs', title:'Ferdi Alici, Ouchhh Studio — First AI Art in Space — KIKK24', desc:'OUCHHH Studio at KIKK 2024: first AI art in space and the Human Cell Atlas project', src:'KIKK' },
  { id:'int_021', cat:'interactive', type:'youtube', vid:'JD3O2ascuvY', title:'Studio DRIFT — Kinetic Installation Placing Viewer in Moving Field', desc:'Studio DRIFT latest kinetic installation with field of moving elements', src:'Studio DRIFT' },
  { id:'int_022', cat:'interactive', type:'youtube', vid:'r-R5Hcwz92U', title:'Studio DRIFT — Pushing Boundaries of Art and Technology', desc:'Studio DRIFT short clip on merging art and technology for unforgettable experiences', src:'Studio DRIFT' },
  { id:'int_023', cat:'interactive', type:'youtube', vid:'uI-B0uXnEp0', title:'Coded Coincidence — Studio DRIFT', desc:'Studio DRIFT\'s Coded Coincidence: appreciating beauty and chance in our world', src:'Studio DRIFT' },
  { id:'int_024', cat:'interactive', type:'youtube', vid:'BMIrkdHEvj4', title:'I AM STORM Exhibition — DRIFT', desc:'Studio DRIFT\'s I Am Storm: visitors become the wind in immersive kinetic artwork', src:'Studio DRIFT' },
  { id:'int_025', cat:'interactive', type:'youtube', vid:'5OL_QI_4V3A', title:'Flylight — Studio DRIFT', desc:'Studio DRIFT\'s Flylight: ever-changing light patterns on kinetic installation', src:'Studio DRIFT' },
  { id:'int_026', cat:'interactive', type:'youtube', vid:'c5Ew8IPohSk', title:'Installation of Shylight — Pinakothek Der Moderne, München', desc:'Studio DRIFT Shylight installation in the Rotunda of Pinakothek der Moderne, Germany', src:'Studio DRIFT' },
  { id:'int_027', cat:'interactive', type:'youtube', vid:'QnwBs8P-z08', title:'Murmuring Minds — DRIFT Interactive Performance at LUMA Arles', desc:'Studio DRIFT\'s Murmuring Minds interactive performance installation at LUMA Arles 2024', src:'Studio DRIFT' },
  { id:'int_028', cat:'interactive', type:'youtube', vid:'UU14ZvAt0nw', title:'Studio DRIFT — Meadow at Denver Art Museum Biophilia Exhibit', desc:'Studio DRIFT\'s Meadow artwork at Denver Art Museum\'s Biophilia exhibition', src:'Studio DRIFT' },
  { id:'int_029', cat:'interactive', type:'youtube', vid:'xDoXUIP07ng', title:'Explore Coded Nature by DRIFT at LUMA Arles', desc:'Studio DRIFT\'s Coded Nature exhibition at LUMA Arles 2024', src:'Studio DRIFT' },
  { id:'int_030', cat:'interactive', type:'youtube', vid:'KvEYeqjuyFo', title:'DRIFT Shy Society — Palazzo Strozzi', desc:'Studio DRIFT\'s spectacular site-specific Shy Society installation at Palazzo Strozzi Oct 2024', src:'Palazzo Strozzi' },
  { id:'int_031', cat:'interactive', type:'youtube', vid:'bDPJWtvutsU', title:'Creator Session with Onformative', desc:'Onformative founders Julia Laub and Cedric Kiefer on evolving their generative art practice', src:'The Interactive & Immersive HQ' },
  { id:'int_032', cat:'interactive', type:'youtube', vid:'7O8YCj2vzQg', title:'Onformative\'s Digital AI Sculptures Warp Our Perception of Time', desc:'Berlin studio onformative creates digital and interactive artworks exploring time and human perception', src:'STIR' },
  { id:'int_033', cat:'interactive', type:'youtube', vid:'wSGG9oPUfvk', title:'Onformative: Delegating within a Creative Team', desc:'Onformative on creative team delegation and workflow in generative art studio', src:'The Interactive & Immersive HQ' },
  { id:'int_034', cat:'interactive', type:'youtube', vid:'syaraklJSNw', title:'Onformative: Staying up to Date on Industry Trends', desc:'Onformative on staying current with interactive and immersive industry trends', src:'The Interactive & Immersive HQ' },
  { id:'int_035', cat:'interactive', type:'youtube', vid:'vnRnvdgxMLw', title:'Meandering River by Onformative', desc:'Onformative audiovisual art installation inspired by the movement of rivers', src:'HIVEH' },
  { id:'int_036', cat:'interactive', type:'youtube', vid:'wM1fX_gK1Mk', title:'Marshmallow Laser Feast: Works of Nature at ACMI — Panasonic', desc:'Marshmallow Laser Feast\'s Works of Nature large-scale interactive exhibition at ACMI Melbourne', src:'Panasonic Australia' },
  { id:'int_037', cat:'interactive', type:'youtube', vid:'kFcLNoDF-Nk', title:'Breathing with the Forest by Marshmallow Laser Feast', desc:'Marshmallow Laser Feast: immersive experience of shared breath with the Amazon rainforest', src:'Emergence Magazine' },
  { id:'int_038', cat:'interactive', type:'youtube', vid:'iYheV0Xt0TQ', title:'In the Studio with Marshmallow Laser Feast — Factory International', desc:'Behind the scenes with Marshmallow Laser Feast pushing boundaries of immersive art', src:'Factory International' },
  { id:'int_039', cat:'interactive', type:'youtube', vid:'VkzAruTtT3U', title:'Introducing Breathing with the Forest by Marshmallow Laser Feast', desc:'Official introduction of Marshmallow Laser Feast\'s immersive Amazon forest experience', src:'Emergence Magazine' },
  { id:'int_040', cat:'interactive', type:'youtube', vid:'pMCkuInRnXs', title:'EVOLVER — Marshmallow Laser Feast — UK Premiere in Oxford', desc:'Marshmallow Laser Feast\'s EVOLVER: immersive journey through the breathing body, narrated by Cate Blanchett', src:'Schwarzman Centre' },
  { id:'int_041', cat:'interactive', type:'youtube', vid:'ikUWlPKvTos', title:'Marshmallow Laser Feast: Where Do You End & Begin? IEN Summit 2024', desc:'Marshmallow Laser Feast at IEN Summit 2024: biosphere, empathy, and immersive art', src:'Immersive Experience Network' },
  { id:'int_042', cat:'interactive', type:'youtube', vid:'E77SMq5Tc94', title:'INCREDIBLE Interactive Projection Mapping', desc:'Immersive and interactive experience with Christie Digital 4K projectors and reactive content', src:'Smart Home Brothers' },
  { id:'int_043', cat:'interactive', type:'youtube', vid:'D16LTDLfmWc', title:'i Light 2024 Kinetic Perspective Geometric Circles Singapore', desc:'Kinetic Perspective light installation at i Light 2024 Singapore — geometric circles with sound', src:'Janice Ong' },
  { id:'int_044', cat:'interactive', type:'youtube', vid:'RroyNd_BR3E', title:'Spin Me a Yarn — i Light 2024 Light Installation Singapore', desc:'Enchanting Spin Me a Yarn light installation at i Light 2024 Singapore', src:'Janice Ong' },
  { id:'int_045', cat:'interactive', type:'youtube', vid:'G-A1FwifoCI', title:'How I Made an Interactive Art Installation (Projection + Sound)', desc:'Artist walkthrough of making CONDU||T interactive projection mapping and sound installation', src:'Left Right' },
  { id:'int_046', cat:'interactive', type:'youtube', vid:'7iCKo1TbFd0', title:'When Form Comes Alive at Hayward Gallery 2024', desc:'When Form Comes Alive exhibition at Hayward Gallery London 2024 — sculptures and installations', src:'Held & Drawn' },
  { id:'int_047', cat:'interactive', type:'youtube', vid:'siSfAbY3Vpg', title:'Japan Pavilion at the 2024 Venice Biennale — Yuko Mohri', desc:'Yuko Mohri\'s kinetic sculptures and sound installations at Japan Pavilion, Venice Biennale 2024', src:'ArtAsForm Tours' },
  { id:'int_048', cat:'interactive', type:'youtube', vid:'MKt0uAd9a1w', title:'FLUX — Interactive Installation at Vilnius Light Festival 2024', desc:'FLUX interactive installation at Vilnius Light Festival 2024 exploring speed of communication', src:'KsaweryKomputeryXVY' },
  { id:'int_049', cat:'interactive', type:'youtube', vid:'Z7AIpuRTEw0', title:'Multimodal Interactive Media Wall — Gyeonggi Ceramic Museum', desc:'IMG LAB multimodal interactive media wall installation at Gyeonggi Ceramic Museum 2024', src:'IMG LAB' },
  { id:'int_050', cat:'interactive', type:'youtube', vid:'tQNKPsHOLro', title:'LG ISE 2025 — Media Art', desc:'LG Information Display media art showcase at ISE 2025 — where technology meets creativity', src:'LG Information Display' },
  { id:'int_051', cat:'interactive', type:'youtube', vid:'02BsIVoqTZY', title:'Immersive Art — Will It Make You Like Art More?', desc:'DW Shift documentary on the booming immersive digital art exhibition phenomenon 2024', src:'DW Shift' },
  { id:'int_052', cat:'interactive', type:'youtube', vid:'WIcWMDo6DOI', title:'FRAMELESS Immersive Art Experience', desc:'FRAMELESS London — largest permanent immersive art experience at Marble Arch, 42 masterpieces', src:'FRAMELESS' },
  { id:'int_053', cat:'interactive', type:'youtube', vid:'J1Yu2ULrKMU', title:'FRAMELESS Immersive Art Experience — The World Around Us Gallery', desc:'FRAMELESS London\'s World Around Us gallery — 4 immersive galleries at Marble Arch', src:'FRAMELESS' },
  { id:'int_054', cat:'interactive', type:'youtube', vid:'4XeSs9a1rLQ', title:'Immersive Art Installation by TUNDRA', desc:'TUNDRA\'s The Day We Left Field: floating meadow immersive audiovisual installation', src:'MoltenArt' },
  { id:'int_055', cat:'interactive', type:'youtube', vid:'oZAot9EZFM0', title:'TUNDRA — THE DAY WE LEFT FIELD Installation (official)', desc:'TUNDRA official video: The Day We Left Field, immersive site-specific audiovisual, São Paulo', src:'TUNDRA' },
  { id:'int_056', cat:'interactive', type:'youtube', vid:'GcCXCAdeIcg', title:'Amazing Immersive Art Installation by TUNDRA — My Whale', desc:'TUNDRA\'s My Whale: thousands of luminous hexagonal modules in interactive immersive installation', src:'MoltenArt' },
  { id:'int_057', cat:'interactive', type:'youtube', vid:'jLMIh5mfaRY', title:'Random International \'Life in a Different Resolution\' — Nxt Museum Amsterdam', desc:'Random International solo exhibition at Nxt Museum Amsterdam 2023-2024', src:'Nxt Museum' },
  { id:'int_058', cat:'interactive', type:'youtube', vid:'Pjl9OOYJyMs', title:'Interactive Rain Room: Walk Through Without Getting Wet!', desc:'Random International\'s Rain Room — walk through rain without getting wet, interactive installation', src:'Weird Art' },
  { id:'int_059', cat:'interactive', type:'youtube', vid:'ogbmbBBNfUE', title:'Brilliant Ideas — Random International — Where Art Meets Algorithm', desc:'Random International documentary — where art meets algorithm in interactive installations', src:'Standart' },
  { id:'int_060', cat:'interactive', type:'youtube', vid:'8pQ3ccIq6EE', title:'Thorne The Frontier Within — Immersive Art Installation & Digital Experience', desc:'UFA case study: Thorne\'s The Frontier Within immersive digital experience 2024', src:'UFA' },
  { id:'int_061', cat:'interactive', type:'youtube', vid:'lhQqSuqUfcE', title:'ARTE Museum NYC — Light, Sound & Immersive Art — Full Walkthrough', desc:'Full walkthrough of ARTE Museum New York City immersive digital art experience', src:'Travel & Taste Tales' },
  { id:'int_062', cat:'interactive', type:'youtube', vid:'QQ-GzeW0yQQ', title:'Interactive Art Installation by Studio DRIFT', desc:'Studio DRIFT skillfully integrating art, technology and nature in compelling interactive experiences', src:'MoltenArt' },
  { id:'int_063', cat:'interactive', type:'youtube', vid:'Nzef-WfcFHo', title:'Top 10 Unbelievable Art Installations 2024', desc:'Top 10 most incredible modern art installations of 2024', src:'TOP 10' },

  // ── 전시 영상 콘텐츠 (2) ────────────────────────────────────────────
  { id:'e1', cat:'exhibition_content', type:'youtube', vid:'Lr_3YyUYptE', title:'LG "Life\'s Good" World Premiere — CES 2026', desc:'CES 2026 LG 월드 프리미어 인튠 영상. 대형 LED 무대 연출.', src:'LG Electronics' },
  { id:'e2', cat:'exhibition_content', type:'youtube', vid:'upMZ1-sBpXU', title:'Everything LG Showed — CES 2026 Full Tour', desc:'CES 2026 LG 프리뷰 스위트 전체 투어. AI Gallery, Alpha11 포함.', src:'LG Electronics' },

  // ── 전시 부스 제작 (2) ──────────────────────────────────────────────
  { id:'b1', cat:'exhibition_booth', type:'youtube', vid:'jIAqIF5tKN8', title:'CES 2026 — LG Booth Tour', desc:'CES 2026 LG 부스 전체 투어. 공간 설계 및 디스플레이 배치 참고.', src:'CES 2026' },
  { id:'b2', cat:'exhibition_booth', type:'youtube', vid:'MD9rfemIOcs', title:'Tour Samsung\'s Booth at CES 2025', desc:'삼성 CES 2025 부스 투어. 대형 전시 공간 구성 및 동선 참고.', src:'Samsung' },

  // ── 브랜드 — LG (48) ───────────────────────────────────────────────
  { id:'lg_001', cat:'lg', type:'youtube', vid:'NrN7kQ2hBeU', title:'JerryRigEverything takes you inside LG\'s CES 2026', desc:'LG CES 2026 부스 투어. \'Innovation in Tune with You\' 테마로 AI 기반 솔루션 전시', src:'LG Global' },
  { id:'lg_002', cat:'lg', type:'youtube', vid:'FeHBnkIHAD8', title:'LG World Premiere – Live: LG at CES 2026', desc:'CES 2026 라스베이거스 LG 월드 프리미어 라이브. #InnovationInTuneWithYou 테마', src:'LG Global' },
  { id:'lg_003', cat:'lg', type:'youtube', vid:'96Jx9AxdCkM', title:'LG CES 2026 Recap', desc:'CES 2026 LG 하이라이트 리캡. AI 기반 솔루션으로 디바이스·공간 연결', src:'LG Global' },
  { id:'lg_004', cat:'lg', type:'youtube', vid:'-9TLSR4X7hY', title:'CES 2026 Reveal: Inside LG Private Booth', desc:'LG Vehicle Solution CES 2026 프라이빗 전시 부스. 모빌리티 넥스트 디멘션', src:'LG Vehicle Solution Global' },
  { id:'lg_005', cat:'lg', type:'youtube', vid:'50S322FnIf8', title:'CES 2026: LG Display Reveals Revolutionary OLED Tech', desc:'CES 2026 LG디스플레이 혁신 OLED 기술 공개. Tandem W-OLED 등', src:'LG Display Global' },
  { id:'lg_006', cat:'lg', type:'youtube', vid:'josYYwWgdzk', title:'Display for AI, Technology for All — LG디스플레이 부스 투어', desc:'LG디스플레이 CES 2026 전시 투어. Tandem OLED 신기술', src:'LG디스플레이' },
  { id:'lg_007', cat:'lg', type:'youtube', vid:'ve4N_YNYTkU', title:'LG unveils 2026 OLED TVs: brighter G6, C6 splits in two, LG W6 Wallpaper OLED', desc:'CES 2026 신형 OLED TV 라인업 공개. G6 20% 밝기 향상, 초슬림 W6', src:'TechRadar' },
  { id:'lg_008', cat:'lg', type:'youtube', vid:'Lr_3YyUYptE', title:'LG "Life\'s Good" World Premiere at CES 2026', desc:'CES 2026 LG Life\'s Good 월드 프리미어 전체 이벤트 영상', src:'CNET' },
  { id:'lg_009', cat:'lg', type:'youtube', vid:'AUYYDSav-a8', title:'LG MicroRGB TVs First Look — CES 2026', desc:'CES 2026 LG MicroRGB TV 기술 첫 공개. RGB 초정밀 픽셀 제어', src:'LA Times Studios' },
  { id:'lg_010', cat:'lg', type:'youtube', vid:'jIAqIF5tKN8', title:'CES 2026 — LG Booth Tour', desc:'CES 2026 LG 부스 투어 영상', src:'techgooch' },
  { id:'lg_011', cat:'lg', type:'youtube', vid:'BQro8lHsmHQ', title:'LG just changed the TV game at CES 2026', desc:'CES 2026 LG 신제품 총정리. OLED, Micro RGB TV, 홈 로봇', src:'GadgetGuy' },
  { id:'lg_012', cat:'lg', type:'youtube', vid:'sxRN_F28aDs', title:'LG\'s TV Lineup Gets Serious at CES 2026', desc:'CES 2026 LG TV 라인업 심층 분석. 주목 모델 집중 조명', src:'AVS Forum' },
  { id:'lg_013', cat:'lg', type:'youtube', vid:'S0ApTemBy-Q', title:'LG\'s World Premiere Event: Everything in 10 Minutes', desc:'LG CES 2026 월드 프리미어 10분 요약. TV·가전·로봇·차량 AI 혁신', src:'CNET' },
  { id:'lg_014', cat:'lg', type:'youtube', vid:'3BQHp0KesAc', title:'CES 2026 Reveal: LG AI-powered In-Vehicle Solutions', desc:'CES 2026 혁신상 수상 LG AI 인-비히클 솔루션 공개', src:'LG Vehicle Solution Global' },
  { id:'lg_015', cat:'lg', type:'youtube', vid:'4aJeGMcuGRo', title:'LG at CES 2025: Highlights', desc:'CES 2025 LG 하이라이트 총정리', src:'LG Global' },
  { id:'lg_016', cat:'lg', type:'youtube', vid:'8rTR_ZJiiKw', title:'LG at CES 2025: Booth Tour with JerryRigEverything', desc:'CES 2025 LG 부스 JerryRigEverything 가이드 투어', src:'LG Global' },
  { id:'lg_017', cat:'lg', type:'youtube', vid:'JU6wkLTHNg4', title:'LG\'s Transparent TV Booth Tour at CES 2025', desc:'CES 2025 LG 투명 TV 포함 부스 투어', src:'CNET' },
  { id:'lg_018', cat:'lg', type:'youtube', vid:'pAfkWRv0c_E', title:'LG at CES 2025: LG World Premiere – Live', desc:'CES 2025 LG 월드 프리미어 라이브. Affectionate Intelligence 공개', src:'LG Global' },
  { id:'lg_019', cat:'lg', type:'youtube', vid:'uyIEdsG_nqE', title:'전 세계를 홀린 환상의 TV [CES 2025]', desc:'CES 2025 LG전자 세계 최초 4K 무선 투명 TV 미디어아트 전시', src:'LG그룹' },
  { id:'lg_020', cat:'lg', type:'youtube', vid:'LAL2-DPV2F0', title:'LG VS Company: CES 2025 Teaser', desc:'CES 2025 LG AI 티저. Life\'s Good 비전 예고', src:'LG Global' },
  { id:'lg_021', cat:'lg', type:'youtube', vid:'DdGUCSTavnA', title:'2025 LG OLED evo AI: See the details of every light and dark', desc:'2025 LG OLED evo AI TV 광고. 빛과 어둠의 세밀한 디테일 표현', src:'LG Global' },
  { id:'lg_022', cat:'lg', type:'youtube', vid:'LugNfRczCk0', title:'LG SIGNATURE: Transparent OLED', desc:'LG 시그니처 OLED T 세계 최초 투명 무선 TV 소개', src:'LG Global' },
  { id:'lg_023', cat:'lg', type:'youtube', vid:'Y9a2Te4tIkA', title:'2024 LG UltraGear OLED: Introduction Film — 32GS95UE', desc:'LG UltraGear OLED 32GS95UE 게이밍 모니터 소개 필름', src:'LG Global' },
  { id:'lg_024', cat:'lg', type:'youtube', vid:'OcIfbobRSbw', title:'We don\'t make life good, you do — Life\'s Good — LG', desc:'LG 브랜드 캠페인 Life\'s Good - 삶을 만드는 건 당신', src:'LG Global' },
  { id:'lg_025', cat:'lg', type:'youtube', vid:'xMkIx5DqaTs', title:'Life\'s Good — We don\'t make life good, you do.', desc:'LG Life\'s Good 캠페인 2024. 브랜드 철학 영상', src:'LG Global' },
  { id:'lg_026', cat:'lg', type:'youtube', vid:'OVq6qY7QOzE', title:'Smart Life Solution: DOOH — LG', desc:'LG AI 기반 DOOH 광고 솔루션 소개. 타겟 인사이트 활용', src:'LG Global' },
  { id:'lg_027', cat:'lg', type:'youtube', vid:'w9fhVm9gyvI', title:'2024 LG gram Pro: Introduction Film — Level up to pro', desc:'2024 LG gram Pro 노트북 소개 필름', src:'LG Global' },
  { id:'lg_028', cat:'lg', type:'youtube', vid:'Yc487Y8PjCw', title:'LG gram Pro 2-in-1', desc:'LG gram Pro 2-in-1 소개. 시장 최경량 16인치 2-in-1', src:'LG Singapore' },
  { id:'lg_029', cat:'lg', type:'youtube', vid:'O3BkrCgMpxE', title:'LG gram Pro X Artist 수린: From Inspiration to Creation', desc:'아티스트 수린과 함께한 LG gram Pro 크리에이터 캠페인 2024', src:'충근피디' },
  { id:'lg_030', cat:'lg', type:'youtube', vid:'2ndbESXVz04', title:'CES 2025: LG Affectionate Intelligence In Your Bedroom', desc:'CES 2025 LG Affectionate Intelligence 침실 적용 시나리오', src:'Abt Electronics' },
  { id:'lg_031', cat:'lg', type:'youtube', vid:'hx2wz2r0LI0', title:'CES 2025: LG Affectionate Intelligence in Home Office', desc:'CES 2025 LG AI 홈 오피스 시나리오 데모', src:'Abt Electronics' },
  { id:'lg_032', cat:'lg', type:'youtube', vid:'keOxJ1vlc5E', title:'Less artificial. More human — Life\'s Good — LG', desc:'LG AI 캠페인 \'덜 인공적, 더 인간적\'. Affectionate Intelligence 철학', src:'LG Global' },
  { id:'lg_033', cat:'lg', type:'youtube', vid:'_LPWqbU8vsc', title:'Life\'s Good: Affectionate Intelligence — LG', desc:'LG AI에 감성을 더한 Affectionate Intelligence 브랜드 필름', src:'LG Global' },
  { id:'lg_034', cat:'lg', type:'youtube', vid:'Kkct0UVGNLE', title:'What if Affectionate Intelligence came alive at home?', desc:'CES 2026 LG CLOiD 예고 영상. Affectionate Intelligence 홈 로봇', src:'LG Global' },
  { id:'lg_035', cat:'lg', type:'youtube', vid:'XpBjXrK_AOo', title:'LG at IFA 2025: Highlights — Affectionate Intelligence Orchestrated by ThinQ', desc:'IFA 2025 LG ThinQ AI 가전 통합 시스템 하이라이트', src:'LG Global' },
  { id:'lg_036', cat:'lg', type:'youtube', vid:'luGgwLWFkCw', title:'LG at IFA 2024: Highlights — Affectionate Intelligence Home', desc:'IFA 2024 LG Affectionate Intelligence Home 전시 하이라이트', src:'LG Global' },
  { id:'lg_037', cat:'lg', type:'youtube', vid:'bNfmAPKMZr8', title:'LG at IFA 2024: LG AI\'s Green Home', desc:'IFA 2024 LG 스마트 그린홈. 태양광·에너지 절감 AI 솔루션', src:'LG Global' },
  { id:'lg_038', cat:'lg', type:'youtube', vid:'w_qKHejLrQ4', title:'LG at IFA 2024: Just say Hi, LG.', desc:'IFA 2024 LG Self-Driving AI Home Hub 음성 제어 데모', src:'LG Global' },
  { id:'lg_039', cat:'lg', type:'youtube', vid:'JElMcMWUdSU', title:'LG at IFA 2024: AI in the Kitchen', desc:'IFA 2024 LG AI 주방. ThinQ ON 개인화 레시피 추천', src:'LG Global' },
  { id:'lg_040', cat:'lg', type:'youtube', vid:'yOAj20-WEHQ', title:'LG at IFA 2024: Smart Laundry for Exercise Routine', desc:'IFA 2024 LG AI 세탁. 운동 스케줄 연동 자동 세탁 시나리오', src:'LG Global' },
  { id:'lg_041', cat:'lg', type:'youtube', vid:'QC7r6bDPSvo', title:'Insane LG entrance at IFA 2024', desc:'IFA 2024 LG 전시관 입구 비주얼 임팩트', src:'Tech Notice' },
  { id:'lg_042', cat:'lg', type:'youtube', vid:'2BZy3OJeAbs', title:'LG at CES 2024: World\'s First 4K Wireless Transparent TV', desc:'CES 2024 LG 시그니처 OLED T 세계 최초 4K 무선 투명 TV 공개', src:'LG Global' },
  { id:'lg_043', cat:'lg', type:'youtube', vid:'vDGs6HtmrH8', title:'LG Global CES 2025', desc:'CES 2025 LG 예고. 라스베이거스를 물들인 Life\'s Good 레드', src:'LG Global' },
  { id:'lg_044', cat:'lg', type:'youtube', vid:'O1SOdXEa7bs', title:'LG\'s CES 2025 Lineup: AI Cars, Bendable Monitors, and Transparent TVs', desc:'CES 2025 LG 전체 라인업 소개. AI 차량, 벤더블 모니터, 투명 TV', src:'GadgetGuy' },
  { id:'lg_045', cat:'lg', type:'youtube', vid:'fpNS0I-Kdck', title:'Unveiling New Digital Worlds via LG Signature OLED T at Frieze London 2025', desc:'Frieze London 2025 LG OLED 아트 전시. 디지털 아트 융합', src:'LG OLED ART' },
  { id:'lg_046', cat:'lg', type:'youtube', vid:'8xEsb5OBK6A', title:'LG Display\'s 2024, in 2 minutes', desc:'LG디스플레이 2024 한 해 성과 요약 2분 영상', src:'LG Display Global' },
  { id:'lg_047', cat:'lg', type:'youtube', vid:'zS7WKp9z7xU', title:'InfoComm 2024: LG 55-Inch Interactive Transparent Touch OLED', desc:'InfoComm 2024 LG 55인치 인터랙티브 투명 터치 OLED 리테일 디스플레이 데모', src:'LG for Business USA' },
  { id:'lg_048', cat:'lg', type:'youtube', vid:'kJAU8qNnyR0', title:'LG VS Company at CES 2025: LG Mobility Innovation Now', desc:'CES 2025 LG VS컴퍼니 모빌리티 이노베이션 현황 발표', src:'LG Global' },

  // ── 브랜드 — 삼성 (45) ─────────────────────────────────────────────
  { id:'sam_001', cat:'samsung', type:'youtube', vid:'3i1OB6wKYms', title:'Introducing Galaxy S25 Ultra — Galaxy AI — Samsung', desc:'갤럭시 S25 Ultra 공식 소개 필름. AI 컴패니언 기능 전면 강조', src:'Samsung' },
  { id:'sam_002', cat:'samsung', type:'youtube', vid:'nFqEOB8M0eY', title:'Introducing Galaxy S25 FE — Samsung', desc:'갤럭시 S25 FE 공식 소개. Galaxy AI 카메라 크리에이티브 기능', src:'Samsung' },
  { id:'sam_003', cat:'samsung', type:'youtube', vid:'FCMFh07nX4Y', title:'Galaxy S25 Edge: Beyond slim — Samsung', desc:'갤럭시 S25 Edge. 역대 가장 슬림한 Galaxy S 시리즈, 티타늄 소재', src:'Samsung India' },
  { id:'sam_004', cat:'samsung', type:'youtube', vid:'sGZrq4EjhEY', title:'Filmed #withGalaxy S25 Ultra — Behind The Scenes of We Are Ocean', desc:'갤럭시 S25 Ultra로 촬영한 오션 다큐멘터리 비하인드', src:'Samsung' },
  { id:'sam_005', cat:'samsung', type:'youtube', vid:'I36GZfxp2LA', title:'Filmed #withGalaxy S25 Ultra — We Are Ocean by Jonathan Clay', desc:'S25 Ultra 촬영 Jonathan Clay 오션 다큐멘터리 풀버전', src:'Samsung' },
  { id:'sam_006', cat:'samsung', type:'youtube', vid:'3hPoEmlBQdY', title:'Introducing Galaxy S24 Ultra — Galaxy AI — Samsung', desc:'갤럭시 S24 Ultra 공식 소개. Galaxy AI 최초 탑재', src:'Samsung' },
  { id:'sam_007', cat:'samsung', type:'youtube', vid:'ePdbj2bZ-Ro', title:'Galaxy S24 Series: Design Film — Samsung', desc:'갤럭시 S24 시리즈 디자인 필름', src:'Samsung' },
  { id:'sam_008', cat:'samsung', type:'youtube', vid:'hm7EhZUbeHg', title:'Samsung × Paris 2024: Open Always Wins – The Next Wave', desc:'파리 2024 올림픽 삼성 파트너십. 서핑 다큐멘터리 필름', src:'Samsung' },
  { id:'sam_009', cat:'samsung', type:'youtube', vid:'aZ4OazyWm8A', title:'Samsung × Paris 2024: Breaking Boundaries', desc:'파리 2024 삼성. 브레이킹 다큐멘터리 브랜드 필름', src:'Samsung' },
  { id:'sam_010', cat:'samsung', type:'youtube', vid:'sIDxNag4b90', title:'Powering The World\'s Logistics, SAMSUNG SDS — Brand film 2024', desc:'삼성SDS 2024 브랜드 필름. 글로벌 물류 솔루션 스토리텔링', src:'Samsung SDS Global' },
  { id:'sam_011', cat:'samsung', type:'youtube', vid:'Orup6m9j7hw', title:'We went hands-on at Samsung\'s First Look at CES 2026', desc:'CES 2026 삼성 퍼스트룩 핸즈온. 주목 신제품 총정리', src:'CNN' },
  { id:'sam_012', cat:'samsung', type:'youtube', vid:'5__aVs_Nuwg', title:'Samsung First Look CES 2026 Quick Booth Tour', desc:'CES 2026 삼성 TV·오디오·홈시어터 신제품 부스 투어', src:'ecoustics' },
  { id:'sam_013', cat:'samsung', type:'youtube', vid:'GlUetQEgwX4', title:'Samsung\'s The First Look Event at CES 2026', desc:'CES 2026 삼성 퍼스트룩 키노트 전체 영상', src:'CNET' },
  { id:'sam_014', cat:'samsung', type:'youtube', vid:'0oJ7jSRJBAA', title:'Samsung Reveals Powerful New Innovations at CES 2026', desc:'CES 2026 삼성 신제품 혁신 하이라이트', src:'Samsung US' },
  { id:'sam_015', cat:'samsung', type:'youtube', vid:'hPdEMp1fOA4', title:'Official Replay — The First Look 2026 — Samsung', desc:'CES 2026 삼성 퍼스트룩 공식 리플레이. AI Living 컴패니언 비전', src:'Samsung' },
  { id:'sam_016', cat:'samsung', type:'youtube', vid:'00HUXoMGbmQ', title:'Samsung\'s The First Look Event: Everything in 10 Minutes', desc:'CES 2026 삼성 퍼스트룩 10분 요약', src:'CNET' },
  { id:'sam_017', cat:'samsung', type:'youtube', vid:'f0_IQ5vQJJk', title:'The First Look 2026 — Official Trailer — Samsung', desc:'CES 2026 삼성 퍼스트룩 공식 트레일러', src:'Samsung' },
  { id:'sam_018', cat:'samsung', type:'youtube', vid:'CduoDFBzFAc', title:'The New Samsung TV Technology at CES 2026 is Insane', desc:'CES 2026 삼성 신규 TV 기술 심층 분석', src:'AVForums' },
  { id:'sam_019', cat:'samsung', type:'youtube', vid:'t_VuLtgqYrg', title:'Samsung shows off every stretchable, rollable, pin-able screen at CES 2025', desc:'CES 2025 삼성 신개념 디스플레이 총출동. 스트레처블·롤러블·핀어블', src:'The Verge' },
  { id:'sam_020', cat:'samsung', type:'youtube', vid:'Qp2aK1P0Pgw', title:'IFA 2024 – Samsung AI Enhances 1930 Einstein Speech', desc:'IFA 2024 삼성 AI 기술로 1930년 아인슈타인 연설 복원 시연', src:'Image Matrix Tech' },
  { id:'sam_021', cat:'samsung', type:'youtube', vid:'imEqfFw5j5U', title:'The Journey of SmartThings — Samsung IFA 2024', desc:'IFA 2024 삼성 SmartThings 여정. 연결된 생활 비전', src:'Samsung' },
  { id:'sam_022', cat:'samsung', type:'youtube', vid:'0iG9F3NQNKM', title:'SAMSUNG IFA 2024 – Flexcam & Breaking', desc:'IFA 2024 삼성 FlexCam과 브레이킹 콘텐츠 비주얼 디자인', src:'IMG LAB' },
  { id:'sam_023', cat:'samsung', type:'youtube', vid:'5FiGeHqML04', title:'삼성전자 IFA 2024 프레스 컨퍼런스 하이라이트', desc:'IFA 2024 삼성전자 프레스 컨퍼런스. AI for All 비전 발표', src:'삼성전자 뉴스룸' },
  { id:'sam_024', cat:'samsung', type:'youtube', vid:'GEVZZW2DWIU', title:'Samsung IFA Press Conference 2025', desc:'IFA 2025 삼성 프레스. AI Home: Future Living, Now 비전', src:'Samsung' },
  { id:'sam_025', cat:'samsung', type:'youtube', vid:'2pi503_ItsI', title:'Invitation for Galaxy Unpacked February 2026 — Samsung', desc:'갤럭시 언팩 2026년 2월 초청장. Galaxy AI 일상 혁신', src:'Samsung' },
  { id:'sam_026', cat:'samsung', type:'youtube', vid:'SA93zbnoR4U', title:'Official Replay — Galaxy Unpacked February 2026 — Samsung', desc:'갤럭시 언팩 2026년 2월 공식 리플레이. S26 시리즈·Buds4 공개', src:'Samsung' },
  { id:'sam_027', cat:'samsung', type:'youtube', vid:'5X7lUY5-ASE', title:'Invitation for Galaxy Unpacked July 2025 — Samsung', desc:'갤럭시 언팩 2025년 7월 초청장. 폴더블 신제품 예고', src:'Samsung' },
  { id:'sam_028', cat:'samsung', type:'youtube', vid:'0cMS8qECR0A', title:'Official Replay — Galaxy Unpacked July 2025 — Samsung', desc:'갤럭시 언팩 2025년 7월 공식 리플레이. Z Fold7·Z Flip7 공개', src:'Samsung' },
  { id:'sam_029', cat:'samsung', type:'youtube', vid:'MTtiyKc8f2g', title:'Ultra Unfolds — Galaxy Z Fold7 — Samsung', desc:'갤럭시 Z Fold7. 역대 가장 슬림·가볍고 내구성 높은 폴드', src:'Samsung' },
  { id:'sam_030', cat:'samsung', type:'youtube', vid:'lj2geATWKw4', title:'2024 Neo QLED 8K: Upscale Every Moment — Samsung', desc:'2024 삼성 Neo QLED 8K AI TV 광고. 모든 순간을 업스케일', src:'Samsung Canada' },
  { id:'sam_031', cat:'samsung', type:'youtube', vid:'f8M9wRH7J74', title:'2024 Neo QLED 8K: Live Sports Upscaled — Samsung', desc:'2024 Neo QLED 8K 라이브 스포츠 업스케일링 광고', src:'Samsung UK' },
  { id:'sam_032', cat:'samsung', type:'youtube', vid:'4ks87Jvr_Jk', title:'2026 Neo QLED: Feature Film — Samsung', desc:'2026 삼성 Neo QLED 피처 필름. Quantum Mini LED 정밀 명암', src:'Samsung' },
  { id:'sam_033', cat:'samsung', type:'youtube', vid:'tTRPxBfpprY', title:'Real QLED: The Clown Behind It All — Samsung', desc:'삼성 Real QLED 캠페인. 가짜 QLED를 풍자한 스토리텔링 광고', src:'Samsung' },
  { id:'sam_034', cat:'samsung', type:'youtube', vid:'A2HqZnKIViI', title:'Bespoke Refrigerator with AI Family Hub — BESPOKE AI 2024', desc:'삼성 비스포크 AI 냉장고 2024. AI 식품 관리 기능', src:'Samsung' },
  { id:'sam_035', cat:'samsung', type:'youtube', vid:'maqaWndUNJQ', title:'Bespoke AI Laundry Combo — BESPOKE AI 2024 — Samsung', desc:'삼성 비스포크 AI 세탁기+건조기 콤보 2024 광고', src:'Samsung' },
  { id:'sam_036', cat:'samsung', type:'youtube', vid:'9Mi08fj8-s0', title:'Life opens up with Galaxy — Samsung', desc:'갤럭시로 열리는 삶. 삼성 혁신 브랜드 캠페인', src:'Samsung' },
  { id:'sam_037', cat:'samsung', type:'youtube', vid:'2gYqEi8-am4', title:'Introducing Galaxy S26 Ultra — Galaxy AI — Samsung', desc:'갤럭시 S26 Ultra 공식 소개. AI로 더 쉽고 효율적인 일상', src:'Samsung' },
  { id:'sam_038', cat:'samsung', type:'youtube', vid:'VmY9nPrxEY8', title:'Privacy Display — Galaxy S26 Ultra — Samsung', desc:'갤럭시 S26 Ultra 세계 최초 모바일 Privacy Display 공개', src:'Samsung' },
  { id:'sam_039', cat:'samsung', type:'youtube', vid:'dHoVUajjwaM', title:'The Devil Wears Prada 2 — Galaxy S26 Ultra — Samsung', desc:'갤럭시 S26 Ultra × 악마는 프라다를 입는다 2 콜라보 광고', src:'Samsung' },
  { id:'sam_040', cat:'samsung', type:'youtube', vid:'OB9w8iY9DCg', title:'Introducing Galaxy Book4 Series — Samsung', desc:'갤럭시 북4 시리즈 소개. AI 콘텐츠 크리에이션 최적 노트북', src:'Samsung' },
  { id:'sam_041', cat:'samsung', type:'youtube', vid:'D006jDesRHY', title:'Galaxy S24 Ultra: Emma Myers in Seoul — Filmed #withGalaxy', desc:'갤럭시 S24 Ultra로 촬영한 Emma Myers의 서울 탐방', src:'Samsung Malaysia' },
  { id:'sam_042', cat:'samsung', type:'youtube', vid:'fUaHjE0kwIg', title:'Invitation for Galaxy Event September 2025 — Samsung', desc:'갤럭시 이벤트 2025년 9월 초청장. Galaxy AI 대중화 선언', src:'Samsung' },
  { id:'sam_043', cat:'samsung', type:'youtube', vid:'8DO3W7Jl9ec', title:'Galaxy Event September 2025: Official Livestream — Samsung', desc:'갤럭시 이벤트 2025년 9월 공식 라이브스트림', src:'Samsung Levant' },
  { id:'sam_044', cat:'samsung', type:'youtube', vid:'TynrTOU0eO4', title:'Why Samsung Home Appliances', desc:'삼성 가전 2025 브랜드 필름. 차별화 가치 강조', src:'Samsung' },
  { id:'sam_045', cat:'samsung', type:'youtube', vid:'3CGHX4dEXAQ', title:'Samsung previews TVs and display tech of the future at CES 2026', desc:'CES 2026 삼성 미래 TV·디스플레이 기술 프리뷰. Micro RGB·홀로그램', src:'Mashable' },

  // ── 브랜드 — 애플 (6) ──────────────────────────────────────────────
  { id:'apl_001', cat:'apple', type:'youtube', vid:'uarNiSl_uh4', title:'Apple Event — September 9, 2024', desc:'애플 이벤트 2024년 9월. iPhone 16·Apple Watch·AirPods 공식 발표', src:'Apple' },
  { id:'apl_002', cat:'apple', type:'youtube', vid:'a6RX9kJ01Kw', title:'Apple Intelligence: Clean Up Photos with iPhone 16', desc:'Apple Intelligence 사진 Clean Up 기능 공식 광고', src:'Apple' },
  { id:'apl_003', cat:'apple', type:'youtube', vid:'9P6CrBFqN8c', title:'iPhone 16 Pro — Camera Control — Apple', desc:'iPhone 16 Pro Camera Control 기능 소개 광고', src:'Apple Malaysia' },
  { id:'apl_004', cat:'apple', type:'youtube', vid:'f36QRp24F5c', title:'iPhone 16 Reveal (4K)', desc:'iPhone 16 공식 공개 영상 4K', src:'Apple Spectrum' },
  { id:'apl_005', cat:'apple', type:'youtube', vid:'70gCxCTpvBg', title:'iPhone 16 Pro Reveal (4K)', desc:'iPhone 16 Pro 공식 공개 영상 4K', src:'Apple Spectrum' },
  { id:'apl_006', cat:'apple', type:'youtube', vid:'YP-ukrBVDH8', title:'Apple iPhone 16 Commercial 2024 – Professional Email Ad', desc:'애플 아이폰 16 2024 공식 TV 광고. 프로페셔널 이메일 편', src:'Commercials Ads Review' },

  // ── 영상 광고 — 3D CG (7) ─────────────────────────────────────────
  { id:'cg3d_001', cat:'cg3d', type:'youtube', vid:'iORWYvPweWE', title:'VFX Showreel 2024 | Framestore', desc:'Framestore 2024 연간 쇼릴. 250개 이상의 광고·영화 프로젝트 하이라이트', src:'Framestore' },
  { id:'cg3d_002', cat:'cg3d', type:'youtube', vid:'1HaA5M2_jV4', title:'VFX Showreel 2025 | Framestore', desc:'Framestore 2025 쇼릴. 역대 최다 프로젝트 기록 달성 — 광고·영화·라이드 포함', src:'Framestore' },
  { id:'cg3d_003', cat:'cg3d', type:'youtube', vid:'jkLTz6Cwk5o', title:'The Mill — Games Reel 2024', desc:'The Mill 게임 시네마틱 릴 2024. 어워드 수상 CG 제작 수준 레퍼런스', src:'The Mill' },
  { id:'cg3d_004', cat:'cg3d', type:'youtube', vid:'pyJbVcturHI', title:'The Mill | Crowds Reel', desc:'The Mill 군중 시뮬레이션 릴. 대규모 CG 퍼포먼스 영상 제작 기준선', src:'The Mill' },
  { id:'cg3d_005', cat:'cg3d', type:'youtube', vid:'_tJf-t8kZSI', title:'Accenture Song | VFX Reel', desc:'Accenture Song VFX 릴. 글로벌 브랜드 광고용 CG 비주얼이펙트 쇼케이스', src:'Accenture Song' },
  { id:'cg3d_006', cat:'cg3d', type:'youtube', vid:'ntjkwIXWtrc', title:'Crush! | iPad Pro | Apple 2024', desc:'Apple M4 iPad Pro 런치 광고 2024. 유압 프레스 파괴 시뮬레이션 CGI — 논란과 함께 화제된 광고', src:'Apple' },
  { id:'cg3d_007', cat:'cg3d', type:'youtube', vid:'jVP5ViOdJBM', title:'The all-new iPad Pro — Thinpossible | Apple 2024', desc:'Apple iPad Pro M4 얇기를 강조한 CGI 광고. 벤딩 시뮬레이션과 제품 CG 합성', src:'Apple' },

  // ── 영상 광고 — 2D CG (7) ─────────────────────────────────────────
  { id:'cg2d_001', cat:'cg2d', type:'youtube', vid:'5OF6g3QfhnU', title:'Optious Motion Reel 2024', desc:'Optious 2024 모션 릴. 타이포그래피·브랜드 모션·광고 애니메이션 전문 스튜디오의 기준작', src:'Optious' },
  { id:'cg2d_002', cat:'cg2d', type:'youtube', vid:'1eQzejdClVY', title:'Airbnb × BUCK Animation Commercial Compilation', desc:'BUCK 스튜디오 × Airbnb 2D 애니메이션 광고 컴필레이션. 빅 브랜드 2D CG 캠페인 레퍼런스', src:'BUCK' },
  { id:'cg2d_003', cat:'cg2d', type:'youtube', vid:'8ctmWfcHT-M', title:'Motion & Design Showreel 2024', desc:'2024 모션 디자인 상업 프로젝트 컴필레이션. 방송·광고용 2D 모션 범위 확인용', src:'Motion Design' },
  { id:'cg2d_004', cat:'cg2d', type:'youtube', vid:'6A0cBuIcpxs', title:'Motion Design Showreel 2025 | mynkdzgn', desc:'2025 모션 디자인 쇼릴. 타이포그래피 기반 브랜드 모션 + 광고 애니메이션 하이라이트', src:'mynkdzgn' },
  { id:'cg2d_005', cat:'cg2d', type:'youtube', vid:'dfLOvlu2B4w', title:'2024 Motion Design Show Reel', desc:'2024 커머셜 모션 디자인 릴. 브랜드 광고용 2D CG 스타일 레인지 참고', src:'Motion Design' },
  { id:'cg2d_006', cat:'cg2d', type:'youtube', vid:'XRb_qtVnDIM', title:'2024 Motion Graphics and Animation Demo Reel', desc:'2024 모션그래픽·애니메이션 데모릴. 광고·브로드캐스트·브랜드 2D CG 작업물', src:'Motion Design' },
  { id:'cg2d_007', cat:'cg2d', type:'youtube', vid:'55Z0UWQ-lu8', title:'Motion Design Reel 2024 | Eje in Motion', desc:'Eje in Motion 2024 릴. 방송·브랜드 중심 2D 모션 디자인 스타일 범위', src:'Eje in Motion' },

  // ── 인테리어 (7) ────────────────────────────────────────────────────
  { id:'int2_001', cat:'interior', type:'youtube', vid:'YVC1979DjQU', title:'Louis Vuitton Flagship Store 5th Avenue NYC — Virtual Tour', desc:'뉴욕 5번가 루이비통 플래그십 스토어 가상 투어 2024. 럭셔리 리테일 공간 설계 레퍼런스', src:'NYC Travel' },
  { id:'int2_002', cat:'interior', type:'youtube', vid:'nB5WUXC0ChY', title:'New York Flagship CHANEL — Full Store Tour NYC', desc:'뉴욕 샤넬 플래그십 풀 스토어 투어. 럭셔리 패션 리테일 공간 구성 및 VMD 레퍼런스', src:'Luxury Shopping' },
  { id:'int2_003', cat:'interior', type:'youtube', vid:'iNnQcg7ZD7M', title:'Dior 30 Avenue Montaigne Paris — Luxury Shopping 2024', desc:'파리 디올 본점 30 Montaigne 스토어 투어 2024. 헤리티지 럭셔리 리테일 레퍼런스', src:'Luxury Vlog' },
  { id:'int2_004', cat:'interior', type:'youtube', vid:'2ub1FWrXLF4', title:"On's Flagship Store London — Designed Like a Science Museum", desc:'런던 On 플래그십 스토어. 과학 박물관처럼 설계된 스포츠 브랜드 체험 공간 — 브랜드 경험 설계 레퍼런스', src:'Dezeen' },
  { id:'int2_005', cat:'interior', type:'youtube', vid:'XmQb6r_8kUo', title:'Places: Luxury Retail | Retail Design', desc:'큐레이션된 럭셔리 리테일 공간 모음. 글로벌 플래그십·팝업 인테리어 디자인 레퍼런스 컴필레이션', src:'Retail Design' },
  { id:'int2_006', cat:'interior', type:'youtube', vid:'GeV1lK6SOKc', title:'Paris Luxury Row — Chanel 31 Rue Cambon + Dior 30 Montaigne + LV', desc:'파리 럭셔리 플래그십 투어. 샤넬·디올·루이비통 파리 본점 내부 공간 비교 레퍼런스', src:'Luxury Vlog' },
  { id:'int2_007', cat:'interior', type:'youtube', vid:'asWNexW_mHk', title:'Paris Dior Montaigne — Full Store Tour & Dior Restaurant', desc:'파리 디올 몽테뉴 플래그십 풀 투어. 식당·갤러리·리테일 통합 공간 설계 레퍼런스', src:'Paris Vlog' },

  // ── OOH 추가 (68-77) ──────────────────────────────────────────────
  { id:'ooh_068', cat:'ooh', type:'youtube', vid:'di9r2MBjmEo', title:"St. Patrick's Day — Anamorphic 3D LED DOOH Billboard 2025", desc:"Sue Sha St. Patrick's Day 3D 아나모픽 LED DOOH 빌보드 2025", src:'SUE SHA' },
  { id:'ooh_069', cat:'ooh', type:'youtube', vid:'LfalehjC_j8', title:'Travel Texas 3D DOOH Anamorphic Billboard — Go2 Productions', desc:'Travel Texas 관광 캠페인 3D 아나모픽 DOOH 빌보드, 토론토 2025', src:'Go2 Productions' },
  { id:'ooh_070', cat:'ooh', type:'youtube', vid:'U4lr0cLhyRU', title:'Siemens 3D Anamorphic Billboard — Detroit Huntington Place', desc:'Siemens USA × BCN Visuals 3D 아나모픽 빌보드, 디트로이트 2025', src:'BCN Visuals' },
  { id:'ooh_071', cat:'ooh', type:'youtube', vid:'C7hASSx0imI', title:'Behind-The-Scenes: COX Communications 3D Anamorphic Billboard', desc:'BCN Visuals × COX Communications 3D 아나모픽 제작 비하인드', src:'BCN Visuals' },
  { id:'ooh_072', cat:'ooh', type:'youtube', vid:'cwBXiGfK_hM', title:"COX Communications — The Fiber of Our Being 3D Billboard", desc:'BCN Visuals × COX Communications 라스베이거스 스트립 3D 아나모픽', src:'BCN Visuals' },
  { id:'ooh_073', cat:'ooh', type:'youtube', vid:'U6qwL8DTdh0', title:'Cox Communications — Almost Touch It 3D Billboard Vegas', desc:'BCN Visuals × Cox Communications Vegas Lids 빌딩 3D 아나모픽', src:'BCN Visuals' },
  { id:'ooh_074', cat:'ooh', type:'youtube', vid:'bdTJ7OjMr7o', title:'Anamorphic 3D Billboard CGI Content — Dubai', desc:'두바이 아나모픽 3D 빌보드 CGI 콘텐츠 프로덕션', src:'DigiComm' },
  { id:'ooh_075', cat:'ooh', type:'youtube', vid:'K6xdv0Lnnwc', title:'ISE 2026 — Spectrum 3D Kinetic LED Screen', desc:'ISE 2026 Spectrum 3D 키네틱 LED 스크린 기술 쇼케이스', src:'ISE 2026' },
  { id:'ooh_076', cat:'ooh', type:'youtube', vid:'HclOTF5_aeA', title:'Outdoor Naked Eye 3D LED Billboard — Production 2025', desc:'옥외 네이키드아이 3D LED 빌보드 영상 제작 사례 2025', src:'LED Display' },
  { id:'ooh_077', cat:'ooh', type:'youtube', vid:'IX6B8wZrg2s', title:'Muxwave ISLE 2025 — Holographic Transparent LED Screen', desc:'Muxwave 홀로그래픽 투명 프레임리스 3D LED 스크린, ISLE 2025', src:'Muxwave' },

  // ── Interactive 추가 (64-88) ──────────────────────────────────────
  { id:'int_064', cat:'interactive', type:'youtube', vid:'nztsMfNZhaI', title:'ARTE MUSEUM NEW YORK — Immersive Interactive Experience', desc:'ARTE MUSEUM 뉴욕 Chelsea Piers 이머시브 디지털 아트 워크스루', src:'ARTE MUSEUM' },
  { id:'int_065', cat:'interactive', type:'youtube', vid:'IFLlvlM2i2w', title:'ARTE MUSEUM Las Vegas — Immersive Art Experience', desc:'ARTE MUSEUM 라스베이거스 이머시브 디지털 아트 전체 투어', src:'ARTE MUSEUM' },
  { id:'int_066', cat:'interactive', type:'youtube', vid:'uCWOrEjTVBM', title:'ARTE Museum Las Vegas — 4K Immersive Experience', desc:'ARTE Museum 라스베이거스 4K 이머시브 아트 익스피리언스', src:'ARTE MUSEUM' },
  { id:'int_067', cat:'interactive', type:'youtube', vid:'vC6V49zo_HM', title:'ARTE MUSEUM New York — Digital Art Top Attraction NYC', desc:'ARTE MUSEUM 뉴욕 디지털 아트 탑 어트랙션', src:'ARTE MUSEUM' },
  { id:'int_068', cat:'interactive', type:'youtube', vid:'5TLlveXVs1E', title:'ARTE MUSEUM Opens Immersive Digital Art Experience', desc:'ARTE MUSEUM 오픈 이머시브 디지털 아트 전시 공식 영상', src:'ARTE MUSEUM' },
  { id:'int_069', cat:'interactive', type:'youtube', vid:'l57aaeTlU1E', title:'ARTE Museum Vegas — 2-Story 30,000 sqft Immersive Experience', desc:'ARTE Museum 라스베이거스 2층 규모 3만 스퀘어피트 이머시브', src:'ARTE MUSEUM' },
  { id:'int_070', cat:'interactive', type:'youtube', vid:'8oFtr2Xvlfw', title:'The Immersive ARTE Museum Las Vegas', desc:'ARTE Museum 라스베이거스 이머시브 아트 전시 워크스루', src:'ARTE MUSEUM' },
  { id:'int_071', cat:'interactive', type:'youtube', vid:'nj3QYVJICDM', title:'ARTE Museum — Ultimate Immersive Experience Vegas 2025', desc:'ARTE Museum 라스베이거스 2025 얼티밋 이머시브 익스피리언스', src:'ARTE MUSEUM' },
  { id:'int_072', cat:'interactive', type:'youtube', vid:'_s18A8cjWvU', title:'ARTE Museum NYC — Full Walkthrough Amazing Visuals', desc:'ARTE Museum 뉴욕 풀 워크스루, 놀라운 비주얼 레퍼런스', src:'ARTE MUSEUM' },
  { id:'int_073', cat:'interactive', type:'youtube', vid:'e8-qX5H__X0', title:'Alex Prager — Mirage Factory Immersive Installation, Miami 2025', desc:'Alex Prager Mirage Factory 이머시브 인스톨레이션, 마이애미 아트위크 2025', src:'VernissageTV' },
  { id:'int_074', cat:'interactive', type:'youtube', vid:'37uCTMBwnvU', title:"Van Gogh: The Immersive Experience — Denver 2026", desc:'Van Gogh 이머시브 익스피리언스 덴버 오픈, 2026', src:'Local News' },
  { id:'int_075', cat:'interactive', type:'youtube', vid:'zPFkmxwqew4', title:'Interactive Art Installations — Immersive Projection & Museum Guide', desc:'인터랙티브 아트 설치 가이드 — 프로젝션 매핑·뮤지엄·퍼블릭 데코', src:'Art Channel' },
  { id:'int_076', cat:'interactive', type:'youtube', vid:'WhTKBNbMu34', title:'FRAMELESS — Immersive Art Experience London', desc:'FRAMELESS 런던 이머시브 아트 갤러리, 마스터피스를 워크스루로 체험', src:'FRAMELESS' },
  { id:'int_077', cat:'interactive', type:'youtube', vid:'CdcIP0I71Ik', title:'Experience Beyond Van Gogh & Monet — Immersive Art Journey', desc:'Van Gogh · Monet 이머시브 아트 여정, Straz Center', src:'Straz Center' },
  { id:'int_078', cat:'interactive', type:'youtube', vid:'6A9eozoVY3o', title:'New Immersive Experience — Mind Blowing New York 2025', desc:'뉴욕 2025 신규 이머시브 익스피리언스 오픈 소개', src:'NY Live TV' },
  { id:'int_079', cat:'interactive', type:'youtube', vid:'eBVoWaBz2v0', title:'Venice Architecture Biennale 2025 — Walk Tour Highlights', desc:'베니스 건축 비엔날레 2025 워크 투어 하이라이트', src:'Architecture Channel' },
  { id:'int_080', cat:'interactive', type:'youtube', vid:'G8pXH_R7PRA', title:'SINGAPORE ODYSSEA — Full Immersive Walkthrough Tour', desc:'싱가포르 Odyssea 타임트래블 이머시브 전시 풀 워크스루', src:'Travel Vlogger' },
  { id:'int_081', cat:'interactive', type:'youtube', vid:'JC8TcS9VDOQ', title:'PREDATOR BADLANDS — Immersive Brand Experience SDCC 2025', desc:'Predator Badlands 브랜드 이머시브 익스피리언스, San Diego Comic Con 2025', src:'Comic Con' },
  { id:'int_082', cat:'interactive', type:'youtube', vid:'ED9gQk87xJ8', title:'Mercer Labs NYC — Most Insane Immersive Museum', desc:'Mercer Labs 뉴욕 이머시브 뮤지엄 4K 투어', src:'Tech Channel' },
  { id:'int_083', cat:'interactive', type:'youtube', vid:'oikxbI4_vAc', title:'teamLab Borderless Tokyo — Immersive Digital Art Museum Tour', desc:'teamLab Borderless 도쿄 이머시브 디지털 아트 뮤지엄 워크스루', src:'Travel Vlogger' },
  { id:'int_084', cat:'interactive', type:'youtube', vid:'Rc6AYPFNFX4', title:'CONTEXT Art Miami 2025 — Full Walking Tour', desc:'CONTEXT Art Miami 2025 풀 워킹 투어, 마이애미 아트위크', src:'Art Vlogger' },

  // ── LG 추가 (049-062) ─────────────────────────────────────────────
  { id:'lg_049', cat:'lg', type:'youtube', vid:'KQENuwJCt3U', title:"Less artificial. More human | Life's Good — LG Brand Film", desc:'LG Affectionate Intelligence 브랜드 필름 — 일상의 소중한 순간', src:'LG Global' },
  { id:'lg_050', cat:'lg', type:'youtube', vid:'gYRM00Oe2BM', title:"LG's AI Home at CES 2025 — Everything in 11 Minutes", desc:'CES 2025 LG AI Home 솔루션 전체 11분 요약', src:'LG Global' },
  { id:'lg_051', cat:'lg', type:'youtube', vid:'GvLbSQ0Qelo', title:'LG Shows Off CLOiD Home Robot at CES 2026 Keynote', desc:'CES 2026 LG CLOiD 가정용 AI 로봇 공식 공개', src:'LG Global' },
  { id:'lg_052', cat:'lg', type:'youtube', vid:'9vIUmVhM-wE', title:'2026 LG OLED evo AI — The Next OLED TV', desc:'2026년형 LG OLED evo AI — 차세대 OLED TV 소개', src:'LG Global' },
  { id:'lg_053', cat:'lg', type:'youtube', vid:'9lL8eJxQuSs', title:'2026 LG OLED evo AI W6 — Wallpaper TV', desc:'LG OLED W6 9mm 초슬림 벽걸이 TV 2026', src:'LG Global' },
  { id:'lg_054', cat:'lg', type:'youtube', vid:'W0jcAJlFP-g', title:"I Didn't Expect LG to Go This Hard at CES 2025", desc:'CES 2025 LG 혁신 기술 쇼케이스 하이라이트', src:'Tech Review' },
  { id:'lg_055', cat:'lg', type:'youtube', vid:'K8pH6zDChdA', title:'CES 2025 Reveal: Inside LG Private Booth', desc:'CES 2025 LG 프라이빗 전시 부스 내부 공개', src:'LG Vehicle Solution' },
  { id:'lg_056', cat:'lg', type:'youtube', vid:'lV3MMHAvkog', title:"LG's Bendable 5K2K OLED Ultrawide Gaming Monitor — CES 2025", desc:'LG 벤더블 5K2K OLED 울트라와이드 게이밍 모니터, CES 2025', src:'LG Global' },
  { id:'lg_057', cat:'lg', type:'youtube', vid:'6Ebnr6uo7w8', title:'CES 2025: LG ThinQ ON Home Devices', desc:'CES 2025 LG ThinQ ON 홈 디바이스 통합 소개', src:'LG Global' },
  { id:'lg_058', cat:'lg', type:'youtube', vid:'TIiG0JdrQa4', title:'CES 2025: LG Car Intelligence — In-Vehicle AI', desc:'CES 2025 LG 차량용 AI 기술 소개', src:'LG Global' },
  { id:'lg_059', cat:'lg', type:'youtube', vid:'CRJvAoah2jo', title:'LG OLED M3 | Perfection, Unwired', desc:'LG OLED M3 무선 OLED — 완벽한 무선 연결', src:'LG Global' },
  { id:'lg_060', cat:'lg', type:'youtube', vid:'WnQI8bPBnC0', title:'The Ultimate TV — LG OLED TV Commercial', desc:'LG OLED TV 광고 — 최고의 TV 경험', src:'LG Global' },
  { id:'lg_061', cat:'lg', type:'youtube', vid:'WZzciiFfvFM', title:'LG OLED Evo | TV Commercial', desc:'LG OLED Evo 기술 TV 광고', src:'LG Global' },
  { id:'lg_062', cat:'lg', type:'youtube', vid:'sn-AOSxIRAA', title:'Best AI TV 2026? LG AI TV Feature Review', desc:'LG AI TV 2026 기능 체험 — AI 기반 화질 개선 시연', src:'Tech Review' },

  // ── Samsung 추가 (046-057) ────────────────────────────────────────
  { id:'sam_046', cat:'samsung', type:'youtube', vid:'-26bEyHMy08', title:'Official Highlights | Galaxy Unpacked January 2025', desc:'갤럭시 언팩 2025년 1월 공식 하이라이트. S25 시리즈 전체 공개', src:'Samsung Mobile' },
  { id:'sam_047', cat:'samsung', type:'youtube', vid:'HinL5jCy_oI', title:'Official Replay | Galaxy Unpacked January 2025', desc:'갤럭시 언팩 2025년 1월 공식 리플레이 전체 영상', src:'Samsung Mobile' },
  { id:'sam_048', cat:'samsung', type:'youtube', vid:'ghNxfPv9c9A', title:'Official Highlights | Galaxy Unpacked July 2025', desc:'갤럭시 언팩 2025년 7월 공식 하이라이트. Z Fold7·Z Flip7', src:'Samsung Mobile' },
  { id:'sam_049', cat:'samsung', type:'youtube', vid:'j_72m2LfLwM', title:'Samsung Unpacked July 2025 — Foldable Innovation', desc:'갤럭시 언팩 7월 2025 폴더블 혁신 기술 공개', src:'Samsung Mobile' },
  { id:'sam_050', cat:'samsung', type:'youtube', vid:'jERUuwyaEpM', title:'Samsung Galaxy AI Commercial 2025 — Phone Campaign', desc:'삼성 갤럭시 AI 2025 TV 광고 캠페인', src:'Samsung Mobile' },
  { id:'sam_051', cat:'samsung', type:'youtube', vid:'ITXJquX9FqM', title:'Official Replay | Galaxy Event October 2025', desc:'갤럭시 이벤트 2025년 10월 공식 리플레이', src:'Samsung Mobile' },
  { id:'sam_052', cat:'samsung', type:'youtube', vid:'kOcEK5TGXV8', title:'Galaxy AI | Now Brief | Galaxy S25 Ultra', desc:'갤럭시 S25 Ultra Galaxy AI Now Brief 기능 소개', src:'Samsung Mobile' },
  { id:'sam_053', cat:'samsung', type:'youtube', vid:'qzp2ngQ-76A', title:'Official Replay | Galaxy Event September 2025', desc:'갤럭시 이벤트 2025년 9월 공식 리플레이', src:'Samsung Mobile' },
  { id:'sam_054', cat:'samsung', type:'youtube', vid:'JEQaDne_E94', title:'Introducing Galaxy Z Flip7 — Samsung', desc:'갤럭시 Z Flip7 공식 소개 영상', src:'Samsung Mobile' },
  { id:'sam_055', cat:'samsung', type:'youtube', vid:'G9Y92pfrIDQ', title:'Unboxing Galaxy Z Flip7 | Samsung', desc:'갤럭시 Z Flip7 공식 언박싱 영상', src:'Samsung Mobile' },
  { id:'sam_056', cat:'samsung', type:'youtube', vid:'okMf5mqbEKQ', title:'2025 The Frame: Feature Film | Samsung', desc:'2025 삼성 The Frame TV 피처 필름', src:'Samsung Electronics' },
  { id:'sam_057', cat:'samsung', type:'youtube', vid:'kr6EmgFaEew', title:'Introducing the Samsung Galaxy S24 Ultra — Samsung UK', desc:'갤럭시 S24 Ultra 공식 소개, Samsung UK', src:'Samsung UK' },

  // ── Apple 추가 (007-015) ──────────────────────────────────────────
  { id:'apl_007', cat:'apple', type:'youtube', vid:'S74jad3ZmUY', title:'Shot on iPhone — TBWA Media Arts Lab | Cannes Lions 2025', desc:'Apple Shot on iPhone 캠페인 Cannes Lions 2025 수상작', src:'Apple' },
  { id:'apl_008', cat:'apple', type:'youtube', vid:'QkOJ16lrTuk', title:'Shot on iPhone 16 Pro | Chinese New Year — Making of', desc:'Shot on iPhone 16 Pro 중국 춘절 필름 "I Made a Mixtape for You" 메이킹', src:'Apple' },
  { id:'apl_009', cat:'apple', type:'youtube', vid:'mdtcSIAiqRc', title:'Shot on iPhone 16 Pro | Chinese New Year — I Made a Mixtape for You', desc:'iPhone 16 Pro 촬영 중국 춘절 단편 "I Made a Mixtape for You"', src:'Apple' },
  { id:'apl_010', cat:'apple', type:'youtube', vid:'HsxtrQWAqIY', title:'Filmmaker Explains Shot on iPhone — Apple Event', desc:'Shot on iPhone 촬영 노하우, 애플 이벤트 필름메이커 토크', src:'Apple' },
  { id:'apl_011', cat:'apple', type:'youtube', vid:'V3dbG9pAi8I', title:'Behind the Scenes — An Apple Event Shot on iPhone', desc:'Apple Event를 iPhone으로 촬영한 비하인드 스토리', src:'Apple' },
  { id:'apl_012', cat:'apple', type:'youtube', vid:'HVuB_LoUE7Q', title:'Shot on iPhone 16 Pro | Big Man — Behind The Scenes', desc:'Shot on iPhone 16 Pro "Big Man" 장편 영화 비하인드', src:'Apple' },
  { id:'apl_013', cat:'apple', type:'youtube', vid:'xd_LmXNBz5w', title:'Shot on iPhone 15 Pro | Midnight — Takashi Miike', desc:'Shot on iPhone 15 Pro, 미이케 다카시 감독 망가 원작 단편 "Midnight"', src:'Apple' },
  { id:'apl_014', cat:'apple', type:'youtube', vid:'kamsx_g2hnI', title:'Original Shot on iPhone Commercial — Apple', desc:'애플 Shot on iPhone 캠페인 오리지널 광고', src:'Apple' },
  { id:'apl_015', cat:'apple', type:'youtube', vid:'DioEA6YBCrw', title:'Shot on iPhone 16 Pro | Behind the Last Scene — Kore-eda', desc:'Shot on iPhone 16 Pro, 고레에다 히로카즈 감독 단편 비하인드', src:'Apple' },

  // ── CG3D 추가 (008-020) ───────────────────────────────────────────
  { id:'cg3d_008', cat:'cg3d', type:'youtube', vid:'VpiNW-B0Ui8', title:'3D Product Animation Showreel 2025 — CGI Forge', desc:'CGI Forge 시네마틱 제품 애니메이션 릴 2025', src:'CGI Forge' },
  { id:'cg3d_009', cat:'cg3d', type:'youtube', vid:'peiRfRNke24', title:'3D Smart Watch | CGI Cinematic Commercial', desc:'Blender 기반 스마트워치 CGI 시네마틱 광고 제작', src:'Motion Design Studio' },
  { id:'cg3d_010', cat:'cg3d', type:'youtube', vid:'x6jXgRxrQDk', title:'Luxury CGI Perfume Ad — Hyper-Realistic 3D', desc:'하이퍼리얼리스틱 3D CGI 럭셔리 향수 광고', src:'CGI Studio' },
  { id:'cg3d_011', cat:'cg3d', type:'youtube', vid:'l3uYL2b6DPQ', title:'Top 21 CGI Marketing Campaigns of 2024', desc:'2024 최고의 CGI 마케팅 캠페인 21선 컴필레이션', src:'Motion Design' },
  { id:'cg3d_012', cat:'cg3d', type:'youtube', vid:'joJ2dRLgbtA', title:'CGI Advertisements — Opening Doors to Creativity', desc:'CGI 광고 영상 컴필레이션 — 창의성의 새 지평', src:'Animation Channel' },
  { id:'cg3d_013', cat:'cg3d', type:'youtube', vid:'6ItIj5B3WY8', title:'Porsche Cayenne Turbo GT 2024 | Unreal Engine 5 Cinematic', desc:'Unreal Engine 5 기반 포르쉐 Cayenne Turbo GT 시네마틱 CGI 광고', src:'Porsche CGI' },
  { id:'cg3d_014', cat:'cg3d', type:'youtube', vid:'E7pCceDrKmg', title:'The Perfect Porsche Cinematic — 4K CGI', desc:'포르쉐 4K 시네마틱 CGI 광고 제작', src:'Porsche' },
  { id:'cg3d_015', cat:'cg3d', type:'youtube', vid:'UNFflgObJQ0', title:"CGI & VFX Spots — BMW X1: The Wave Director's Cut", desc:"BMW X1 'The Wave' 디렉터스컷 CGI·VFX 광고", src:'BMW' },
  { id:'cg3d_016', cat:'cg3d', type:'youtube', vid:'maPAMfUtuaE', title:'Unreal Precision, BMW Attitude — Unreal Engine 5.5', desc:'BMW 브랜드 필름, Unreal Engine 5.5 실시간 CGI 제작', src:'BMW CGI' },
  { id:'cg3d_017', cat:'cg3d', type:'youtube', vid:'Ri_dcgD1wMQ', title:'Cinematography Breakdown — Filming a Porsche Commercial', desc:'포르쉐 광고 촬영 시네마토그래피 브레이크다운', src:'Production' },
  { id:'cg3d_018', cat:'cg3d', type:'youtube', vid:'Pc0QN460o6s', title:'Porsche: Perfection Unleashed — CGI Brand Film', desc:'포르쉐 Perfection Unleashed CGI 브랜드 필름', src:'Porsche' },
  { id:'cg3d_019', cat:'cg3d', type:'youtube', vid:'tyqFZe53Hcg', title:'BMW 2024 Super Bowl Commercial — CGI', desc:'BMW 2024 슈퍼볼 CGI 광고', src:'BMW' },
  { id:'cg3d_020', cat:'cg3d', type:'youtube', vid:'x1NOVu8Vz38', title:'How We Made a Cinematic Car Commercial — Behind Scenes', desc:'시네마틱 자동차 광고 제작 비하인드 — 촬영·CGI 과정', src:'Production' },
];
